#!/bin/sh
cd ../static/lib
cat \
jquery-1.3.2.min.js \
iso-3166.js \
dependentInputs.js \
jquery.validate.js \
app.js \
comprec.js \
dataTables-1.5/media/js/jquery.dataTables.js \
dragColumns.js \
FixedHeader.js \
records.js \
jquery.scrollTo-1.4.2-min.js \
jquery.simplemodal.1.4.1.js \
GoogleMaps.js \
GoogleAnalytics.js \
> agg.js
cp ../js/agg.js ../js/agg_backup.js
mv agg.js ../js/agg.js
rm ../js/agg_backup.js